// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvnjmmazkftcjqxstoyn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2bmptbWF6a2Z0Y2pxeHN0b3luIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNTcyNTUsImV4cCI6MjA2OTkzMzI1NX0.AYlscj8VbZVrjCoMyixW4Q5oaygV_fUUglCb1617KgM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});